// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0vkc_zvduVjmFw_wpOaNW4BM7XzyYSxI',
    appId: '1:794819253963:web:09ef4612710ae61d87ed4e',
    messagingSenderId: '794819253963',
    projectId: 'e-commerce-app-ad26e',
    authDomain: 'e-commerce-app-ad26e.firebaseapp.com',
    storageBucket: 'e-commerce-app-ad26e.firebasestorage.app',
    measurementId: 'G-PM10K65S0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UeIYfZloCrnalBRg56-EB6izKT6N6TE',
    appId: '1:794819253963:android:433e0aa48791821e87ed4e',
    messagingSenderId: '794819253963',
    projectId: 'e-commerce-app-ad26e',
    storageBucket: 'e-commerce-app-ad26e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmU37EDcVHEc4UpsEd1RfNiDiBwl2-h8c',
    appId: '1:794819253963:ios:a2a3da6ca84cdd8587ed4e',
    messagingSenderId: '794819253963',
    projectId: 'e-commerce-app-ad26e',
    storageBucket: 'e-commerce-app-ad26e.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );
}
